<?php
const DATABASE_CONNECTION_DRIVER='mysql';
const DATABASE_CONNECTION_HOST='localhost';
const DATABASE_CONNECTION_DATABASE_NAME='youredb';
const DATABASE_CONNECTION_CHAR_SET='utf8';
const DATABASE_CONNECTION_USER_ID='root';
const DATABASE_CONNECTION_USER_PASSWORD='root';
const DATABASE_CONNECTION_OPTIONS=[PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION];
const DATABASE_CONNECTION_DSN=DATABASE_CONNECTION_DRIVER.':host='.DATABASE_CONNECTION_HOST.';dbname='.DATABASE_CONNECTION_DATABASE_NAME.';charset='.DATABASE_CONNECTION_CHAR_SET.';';
